# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_auto_20170313_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='slug_id',
            field=models.CharField(default='NElRYdxlTQYa', max_length=12, primary_key=True, serialize=False),
        ),
    ]
