# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_auto_20170313_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='slug_id',
            field=models.CharField(default='ukKha8UAQyVG', max_length=12, primary_key=True, serialize=False),
        ),
    ]
