# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0009_auto_20170314_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='slug_id',
            field=models.CharField(default='p7b9yoSIRiZ2', max_length=12, primary_key=True, serialize=False),
        ),
    ]
