# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0010_auto_20170315_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='slug_id',
            field=models.CharField(default='0u3OddL5ujsp', max_length=12, primary_key=True, serialize=False),
        ),
    ]
