# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0012_auto_20170316_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='slug_id',
            field=models.CharField(default='vmBmA8wKNi2F', max_length=12, primary_key=True, serialize=False),
        ),
    ]
