# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0014_auto_20170318_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='background',
            field=models.CharField(choices=[(b'Acolyte', b'Acolyte'), (b'Charlatan', b'Charlatan'), (b'City Watch', b'City Watch'), (b'Clan Crafter', b'Clan Crafter'), (b'Cloistered Scholar', b'Cloistered Scholar'), (b'Courtier', b'Courtier'), (b'Criminal', b'Criminal'), (b'Entertainer', b'Entertainer'), (b'Faction Agent', b'Faction Agent'), (b'Far Traveller', b'Far Traveler'), (b'Folk hero', b'Folk Hero'), (b'Guild Artisan', b'Guild Artisan'), (b'Haunted One', b'Haunted One'), (b'Hermit', b'Hermit'), (b'Inheritor', b'Inheritor'), (b'Knight of the Order', b'Knight of the Order'), (b'Mercenary Veteran', b'Mercenary Veteran'), (b'Noble', b'Noble'), (b'Outlander', b'Outlander'), (b'Sage', b'Sage'), (b'Sailor', b'Sailor'), (b'Soldier', b'Soldier'), (b'Urban Bounty Hunter', b'Urban Bounty Hunter'), (b'Urchin', b'Urchin'), (b'Uthgardt Tribe Member', b'Uthgardt Tribe Member'), (b'Waterdhavian Noble', b'Waterdhavian Noble')], max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='slug_id',
            field=models.CharField(default='hDeCgMHWI43t', max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(choices=[(b'Undercommon', b'Undercommon'), (b'Deep Speech', b'Deep Speech'), (b'Primordial', b'Primordial'), (b'Aarakocra', b'Aarakocra'), (b'Celestial', b'Celestial'), (b'Dwarvish', b'Dwarvish'), (b'Draconic', b'Draconic'), (b'Halfling', b'Halfling'), (b'Infernal', b'Infernal'), (b'Druidic', b'Druidic'), (b'Abyssal', b'Abyssal'), (b'Gnomish', b'Gnomish'), (b'Common', b'Common'), (b'Elvish', b'Elvish'), (b'Sylvan', b'Sylvan'), (b'Terran', b'Terran'), (b'Goblin', b'Goblin'), (b'Aquan', b'Aquan'), (b'Auran', b'Auran'), (b'Giant', b'Giant'), (b'Gnoll', b'Gnoll'), (b'Ignan', b'Ignan'), (b'Orcish', b'Orc')], max_length=50, primary_key=True, serialize=False),
        ),
    ]
