# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0021_auto_20170324_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='slug_id',
            field=models.CharField(default='LWU8IfuaGmQP', max_length=12, primary_key=True, serialize=False),
        ),
    ]
