# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_premium_account',
            field=models.BooleanField(default=False, verbose_name=b'premium'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_pro_account',
            field=models.BooleanField(default=False, verbose_name=b'pro'),
        ),
    ]
