# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_auto_20170313_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_premium_account',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_pro_account',
        ),
    ]
