# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_auto_20170313_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='DJ4ZU03ztiCVtYO3MwrJr3jX', max_length=24),
        ),
    ]
