# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_user_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='unique_id',
            field=models.CharField(default='tkC6lMu6oO3Y72EvPJtrQcYl', max_length=24),
        ),
    ]
