# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_auto_20170313_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name=b'city'),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=50, verbose_name=b'country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.CharField(default='bcZ24C1Lr4ufzxZ8nITHjdUl', max_length=24),
        ),
    ]
