# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0008_auto_20170314_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_prem_member',
            field=models.BooleanField(default=False, verbose_name=b'premium status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_pro_member',
            field=models.BooleanField(default=False, verbose_name=b'pro status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.CharField(default='Iy3ieMjxXD8AWQXRLDaFgk2w', max_length=24),
        ),
    ]
