# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0009_auto_20170315_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.CharField(default='G5CheP1tN8oaae4ECQ6wwWJ1', max_length=24),
        ),
    ]
