# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0010_auto_20170316_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.CharField(default='JODoYyssa0FSNgVhs4v8dRtZ', max_length=24),
        ),
    ]
