# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0015_auto_20170323_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.CharField(default='DDBJXJIyuVMHZGl1EPTwJLzg', max_length=24),
        ),
    ]
