# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0016_auto_20170323_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.CharField(default='fwbT09Y8d8dBuUMxH2LG3dVE', max_length=24),
        ),
    ]
