# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0017_auto_20170323_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.CharField(default='iU1BHFbqTJfl56BclrumtgTq', max_length=24),
        ),
    ]
